version: "3"
services:
  mongo:
    container_name: mongo-londontravel
    image: mongo:5
    # restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo/data_mongo:/data
    ports:
      - ${MONGO_PORT}:27017
  server:
    container_name: node-backend
    image: node-backend:1.0
    build:
      context: ../
      dockerfile: ./Dockerfiles/builds/server/Dockerfile
    environment:
      - SERVER_PORT=3000
      - MONGO_URI=${SERVER_MONGO_URI}
      - JWT_TOKEN=${SERVER_JWT_TOKEN}
      - NODE_ENV=${SERVER_NODE_ENV}
      - SESSION_SECRET=${SERVER_SESSION_SECRET}
    ports:
      - ${SERVER_HOST_PORT}:3000
    links:
      - mongo
  fe-app:
    container_name: fe-app
    image: fe-app:1.0
    build:
      context: ../
      dockerfile: ./Dockerfiles/builds/fe-app/Dockerfile
    environment:
      - BACKEND_URL=${FE_APP_BACKEND_URL}
    ports:
      - ${FE_APP_HOST_PORT}:80
  ingress:
    container_name: ingress
    image: ingress:1.0
    build:
      context: ../
      dockerfile: ./Dockerfiles/builds/nginx/Dockerfile
    ports:
      - ${NGINX_HOST_PORT_HTTP}:80
      - ${NGINX_HOST_PORT_HTTPS}:443
    volumes:
      - ./Dockerfiles/builds/nginx/ssl:/etc/nginx/ssl
    links:
      - fe-app
      - server
