version: "3"
services:
  mongo:
    container_name: mongo-londontravel
    image: mongo:5
    # restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo/data_mongo:/data
    ports:
      - ${MONGO_PORT}:27017

volumes:
  data_mongo: {}
